-- Create users table
CREATE TABLE IF NOT EXISTS USERS (
    ID VARCHAR(255) PRIMARY KEY,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    ORGANIZATION_ID VARCHAR(255) NOT NULL,
    ORGANIZATION_NAME VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create organizations table
CREATE TABLE IF NOT EXISTS ORGANIZATIONS (
    ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SLUG VARCHAR(255),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS IDX_USERS_EMAIL ON USERS(EMAIL);

CREATE INDEX IF NOT EXISTS IDX_USERS_ORGANIZATION_ID ON USERS(ORGANIZATION_ID);

CREATE INDEX IF NOT EXISTS IDX_ORGANIZATIONS_SLUG ON ORGANIZATIONS(SLUG);

-- Add foreign key constraint
ALTER TABLE USERS
    ADD CONSTRAINT FK_USERS_ORGANIZATION FOREIGN KEY (
        ORGANIZATION_ID
    )
        REFERENCES ORGANIZATIONS(
            ID
        );