-- Migration: Add email verification and user session tables
-- Created: 2024-01-XX

-- Create verification_tokens table
CREATE TABLE IF NOT EXISTS VERIFICATION_TOKENS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    EMAIL VARCHAR(255) NOT NULL,
    TOKEN VARCHAR(255) NOT NULL UNIQUE,
    TYPE VARCHAR(50) NOT NULL, -- 'email_verification', 'password_reset'
    EXPIRES_AT TIMESTAMP NOT NULL,
    USED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Create indexes for verification_tokens
CREATE INDEX IF NOT EXISTS VERIFICATION_TOKENS_EMAIL_IDX ON VERIFICATION_TOKENS(EMAIL);

CREATE INDEX IF NOT EXISTS VERIFICATION_TOKENS_TOKEN_IDX ON VERIFICATION_TOKENS(TOKEN);

CREATE INDEX IF NOT EXISTS VERIFICATION_TOKENS_TYPE_IDX ON VERIFICATION_TOKENS(TYPE);

CREATE INDEX IF NOT EXISTS VERIFICATION_TOKENS_EXPIRES_IDX ON VERIFICATION_TOKENS(EXPIRES_AT);

-- Create user_sessions table
CREATE TABLE IF NOT EXISTS USER_SESSIONS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    USER_ID UUID NOT NULL REFERENCES USERS(ID),
    SESSION_TOKEN VARCHAR(255) NOT NULL UNIQUE,
    EXPIRES_AT TIMESTAMP NOT NULL,
    IP_ADDRESS VARCHAR(45), -- supports IPv6
    USER_AGENT TEXT,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    LAST_ACCESSED_AT TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Create indexes for user_sessions
CREATE INDEX IF NOT EXISTS USER_SESSIONS_USER_IDX ON USER_SESSIONS(USER_ID);

CREATE INDEX IF NOT EXISTS USER_SESSIONS_TOKEN_IDX ON USER_SESSIONS(SESSION_TOKEN);

CREATE INDEX IF NOT EXISTS USER_SESSIONS_EXPIRES_IDX ON USER_SESSIONS(EXPIRES_AT);

CREATE INDEX IF NOT EXISTS USER_SESSIONS_ACTIVE_IDX ON USER_SESSIONS(IS_ACTIVE);

-- Update users table to require email verification
-- Set emailVerifiedAt to NULL for existing users (they'll need to re-verify)
-- In production, you might want to grandfather existing users
UPDATE USERS
SET
    EMAIL_VERIFIED_AT = NULL
WHERE
    EMAIL_VERIFIED_AT IS NOT NULL;

-- Add a comment to track this migration
COMMENT ON TABLE VERIFICATION_TOKENS IS 'Email verification and password reset tokens';
COMMENT ON TABLE USER_SESSIONS IS 'Active user sessions for authentication';